### ISSUE TITLE
check-pid helper script fails on Alpine systems

### ISSUE THREAD

**Issue by hosom** [zeek/broctl#10]
The version of `ps` that ships with Alpine doesn't have a `-p` option. This means that broctl marks all bro processes as crashed. 

There's a python-native option:

```python
import os

def check_pid(pid):
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False

    return True
```

I think that this is reasonable, but I don't know if it is typical for the average Bro deployment to have Python on every node. 

I am happy to put in a PR, but wanted thoughts on the approach first.

**Comment by jsiwek** [comment]
Sticking with a bash solution, seems like `check-pid` could be implemented something like this:

```bash
(kill -0 $1 >/dev/null 2>&1 && pgrep bro | grep -q $1) && echo "running" || echo "not running"
```

**Comment by hosom** [comment]
Tested and works on Alpine. I like your solution better, because it sticks with the current dependency requirements. 

Went ahead and submitted a PR, #11, for this.

**Comment by jsiwek** [comment]
There's an improved version of the script in master now.
